services:
  - type: web
    name: dipvision-apitest
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn apitest.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SECRET_KEY
        value: "replace_this_with_a_secure_value"
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "*"
